### ISSUE TITLE
How to get the image position in docx？

### ISSUE THREAD

**Issue by PeanutHull** [PhilGale92/docx#47]
in the Docx.class.php.
![image](https://cloud.githubusercontent.com/assets/16012516/24347393/bf7c54c8-130a-11e7-8115-1a0ea706bedd.png)

**Comment by PhilGale92** [comment]
The images are positioned by replacing out the w:drawing nodes. The assets
array you found is just where the parser grabs images from the reps.xml
file, so it can inject then in later on.

See Node.Class.php line 540.

On 27 Mar 2017 09:32, "peanut" <notifications@github.com> wrote:

in the Docx.class.php.
[image: image]
<https://cloud.githubusercontent.com/assets/16012516/24347393/bf7c54c8-130a-11e7-8115-1a0ea706bedd.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PhilGale92/docx/issues/47>, or mute the thread
